#!/usr/bin/env bash

# Check if Bluetooth is enabled
bluetooth_status=$(bluetoothctl show | grep "Powered: yes")

if [[ -n "$bluetooth_status" ]]; then
    # Check if any device is connected
    connected_devices=$(bluetoothctl devices Connected | awk '{print $1=$2=$3=""}1')
    # echo $connected_devices   ## DEBUG

    if [[ -n "$connected_devices" ]]; then
        # Extract device names from connected_devices
        # connected_names=$(echo "$connected_devices")
        # echo $connected_names  # DEBUG

        # Print connected device names
        echo -n $connected_devices
    else
        echo "BT ON"
    fi
else
    echo "BT OFF"
fi

